const CONFIG = {
  races: {
    human: {
      name: "人類",
      desc: "適應力強",
      mod: { maxHp: 0.95, atk: 1.0, speed: 1.0 },
    },
    elf: {
      name: "精靈",
      desc: "高速閃避",
      mod: { maxHp: 0.85, atk: 1.05, speed: 1.25 },
    },
    orc: {
      name: "獸人",
      desc: "高攻爆發",
      mod: { maxHp: 1.2, atk: 1.15, speed: 0.85 },
    },
    dwarf: {
      name: "矮人",
      desc: "堅硬格擋",
      mod: { maxHp: 1.1, atk: 0.95, speed: 0.8 },
      traits: ["block"],
    },
    halfling: {
      name: "半身人",
      desc: "幸運閃避",
      mod: { maxHp: 0.7, atk: 0.9, speed: 1.15 },
      traits: ["dodge", "gold"],
    },
    undead: {
      name: "亡靈",
      desc: "吸血/藥水無效",
      mod: { maxHp: 0.6, atk: 1.4, speed: 0.9 },
      hidden: true,
    },
    dragonkin: {
      name: "龍人",
      desc: "全能龍鱗",
      mod: { maxHp: 1.2, atk: 1.2, speed: 1.1 },
      hidden: true,
    },
  },
  classes: {
    // T1
    warrior: {
      name: "戰士",
      desc: "攻守平衡",
      bonus: { maxHp: 15, atk: 4, speed: 0 },
      style: "standard",
      promotesTo: "knight",
    },
    thief: {
      name: "盜賊",
      desc: "二連擊",
      bonus: { maxHp: -10, atk: -3, speed: 15 },
      style: "multi_hit",
      hits: 2,
      promotesTo: "assassin",
    },
    archer: {
      name: "弓手",
      desc: "先制攻擊",
      bonus: { maxHp: -15, atk: 5, speed: 5 },
      style: "preemptive",
      promotesTo: "ranger",
    },
    mage: {
      name: "法師",
      desc: "必中/脆皮",
      bonus: { maxHp: -20, atk: 7, speed: 2 },
      style: "true_strike",
      promotesTo: "archmage",
    },
    cleric: {
      name: "牧師",
      desc: "再生/藥水強",
      bonus: { maxHp: 20, atk: -4, speed: 0 },
      style: "regen",
      promotesTo: "paladin",
    },
    // T2
    knight: {
      name: "皇家騎士",
      desc: "格擋反擊",
      bonus: { maxHp: 50, atk: 12, speed: -5, block: 0.1 },
      style: "counter_attack",
    },
    assassin: {
      name: "暗影刺客",
      desc: "高暴三連擊",
      bonus: { maxHp: -15, atk: 8, speed: 25, crit: 0.15 },
      style: "multi_hit",
      hits: 3,
    },
    ranger: {
      name: "叢林遊俠",
      desc: "先制擊暈",
      bonus: { maxHp: -5, atk: 12, speed: 15 },
      style: "stun_shot",
    },
    archmage: {
      name: "大魔導士",
      desc: "必中/連詠",
      bonus: { maxHp: -25, atk: 22, speed: 5 },
      style: "double_cast",
    },
    paladin: {
      name: "聖騎士",
      desc: "愈戰愈強",
      bonus: { maxHp: 70, atk: 5, speed: -5, hp_regen: 8 },
      style: "scaling_atk",
    },
    // Hidden
    berserker: {
      name: "狂戰士",
      desc: "殘血加攻",
      bonus: { maxHp: 40, atk: 8, speed: -5 },
      hidden: true,
      unlockCheck: (p) => p.currentHp / p.stats.maxHp <= 0.1,
    },
    merchant: {
      name: "豪商",
      desc: "金錢之力",
      bonus: { maxHp: 0, atk: 0, speed: 0 },
      hidden: true,
      unlockCheck: (p) => p.gold >= 3000,
    },
    gambler: {
      name: "賭徒",
      desc: "極運極險",
      bonus: { maxHp: -20, atk: 10, speed: 10, crit: 0.5, dodge: -1.0 },
      hidden: true,
      unlockCheck: (p) => false,
    },
  },
  biomes: {
    plains: {
      name: "新手平原",
      icon: "🌱",
      color: "#8bc34a",
      minDepth: 0,
      set: "adventurer",
      scaling: 1.0,
      monsters: ["slime", "wolf", "bat"],
      boss: "gnoll_king",
    },
    forest: {
      name: "迷霧森林",
      icon: "🌲",
      color: "#2e7d32",
      minDepth: 20,
      set: "forest",
      scaling: 2.0,
      monsters: ["slime", "wolf", "ent"],
      boss: "ancient_treant",
    },
    cave: {
      name: "廢棄礦坑",
      icon: "⛏️",
      color: "#795548",
      minDepth: 50,
      set: "miner",
      scaling: 4.0,
      monsters: ["goblin", "bat", "rock_golem"],
      boss: "troll",
    },
    volcano: {
      name: "焦熱地獄",
      icon: "🌋",
      color: "#d32f2f",
      minDepth: 100,
      set: "flame",
      scaling: 8.0,
      monsters: ["fire_imp", "hell_hound"],
      boss: "dragon",
    },
    tundra: {
      name: "凜冬雪原",
      icon: "❄️",
      color: "#4fc3f7",
      minDepth: 150,
      set: "glacial",
      scaling: 16.0,
      monsters: ["ice_wolf", "yeti", "ice_elemental"],
      boss: "frost_giant",
    },
    graveyard: {
      name: "幽暗墓地",
      icon: "🪦",
      color: "#9e9e9e",
      minDepth: 200,
      set: "necro",
      scaling: 32.0,
      monsters: ["skeleton", "zombie", "ghost"],
      boss: "lich",
    },
    desert: {
      name: "炙熱沙漠",
      icon: "🏜️",
      color: "#ffb74d",
      minDepth: 250,
      set: "sandstorm",
      scaling: 64.0,
      monsters: ["sandworm", "scorpion", "mummy"],
      boss: "sphinx",
    },
    abyss: {
      name: "歸墟", // The Void
      icon: "⚫",
      color: "#000000",
      minDepth: 500,
      set: "void",
      scaling: 500.0,
      monsters: ["void_walker", "entropy_avatar", "forgotten_god"],
      boss: "azathoth",
    },
  },
  monsters: {
    // Plains
    slime: {
      name: "史萊姆",
      icon: "💧",
      baseHp: 25,
      baseAtk: 6,
      speed: 60,
      gold: 3,
      type: "common",
      mat: "slime_gel",
    },
    wolf: {
      name: "野狼",
      icon: "🐺",
      baseHp: 50,
      baseAtk: 12,
      speed: 105,
      gold: 7,
      type: "common",
      mat: "wolf_fang",
    },
    bat: {
      name: "蝙蝠",
      icon: "🦇",
      baseHp: 30,
      baseAtk: 9,
      speed: 125,
      gold: 5,
      type: "common",
      mat: "bat_wing",
    },
    gnoll_king: {
      name: "豺狼人王",
      icon: "🦁",
      baseHp: 500,
      baseAtk: 35,
      speed: 85,
      gold: 200,
      type: "boss",
      mat: "wind_crest",
    },

    // Forest/Cave/Volcano (Existing)
    goblin: {
      name: "哥布林",
      icon: "👺",
      baseHp: 45,
      baseAtk: 10,
      speed: 90,
      gold: 8,
      type: "common",
      mat: "cloth",
    },
    ent: {
      name: "樹人",
      icon: "🌳",
      baseHp: 180,
      baseAtk: 25,
      speed: 40,
      gold: 30,
      type: "elite",
      mat: "ancient_wood",
    },
    rock_golem: {
      name: "岩石怪",
      icon: "🗿",
      baseHp: 250,
      baseAtk: 30,
      speed: 30,
      gold: 40,
      type: "elite",
      mat: "iron_ore",
    },
    fire_imp: {
      name: "火焰小鬼",
      icon: "😈",
      baseHp: 100,
      baseAtk: 35,
      speed: 130,
      gold: 35,
      type: "elite",
      mat: "fire_essence",
    },
    hell_hound: {
      name: "地獄犬",
      icon: "🐕",
      baseHp: 150,
      baseAtk: 45,
      speed: 120,
      gold: 50,
      type: "elite",
      mat: "hell_leather",
    },
    ancient_treant: {
      name: "遠古樹精",
      icon: "🎄",
      baseHp: 1200,
      baseAtk: 80,
      speed: 35,
      gold: 600,
      type: "boss",
      mat: "life_seed",
    },
    troll: {
      name: "巨魔",
      icon: "🧟",
      baseHp: 1500,
      baseAtk: 90,
      speed: 55,
      gold: 700,
      type: "boss",
      mat: "earth_shard",
    },
    dragon: {
      name: "紅龍",
      icon: "🐉",
      baseHp: 4000,
      baseAtk: 180,
      speed: 95,
      gold: 2000,
      type: "boss",
      mat: "eternal_ember",
    },

    // Tundra
    ice_wolf: {
      name: "冰狼",
      icon: "🐺",
      baseHp: 180,
      baseAtk: 50,
      speed: 115,
      gold: 60,
      type: "common",
      mat: "permafrost",
    },
    yeti: {
      name: "雪怪",
      icon: "🦍",
      baseHp: 400,
      baseAtk: 80,
      speed: 50,
      gold: 100,
      type: "elite",
      mat: "permafrost",
    },
    ice_elemental: {
      name: "冰元素",
      icon: "❄️",
      baseHp: 250,
      baseAtk: 60,
      speed: 90,
      gold: 80,
      type: "common",
      mat: "permafrost",
    },
    frost_giant: {
      name: "冰霜巨人",
      icon: "🥶",
      baseHp: 6000,
      baseAtk: 250,
      speed: 40,
      gold: 3000,
      type: "boss",
      mat: "frozen_heart",
    },

    // Graveyard
    skeleton: {
      name: "骷髏兵",
      icon: "💀",
      baseHp: 200,
      baseAtk: 70,
      speed: 80,
      gold: 70,
      type: "common",
      mat: "soul_dust",
    },
    zombie: {
      name: "腐屍",
      icon: "🧟‍♂️",
      baseHp: 500,
      baseAtk: 50,
      speed: 30,
      gold: 80,
      type: "common",
      mat: "cloth",
    },
    ghost: {
      name: "幽靈",
      icon: "👻",
      baseHp: 150,
      baseAtk: 90,
      speed: 130,
      gold: 90,
      type: "elite",
      mat: "soul_dust",
    },
    lich: {
      name: "不死巫妖",
      icon: "🧙‍♂️",
      baseHp: 5000,
      baseAtk: 300,
      speed: 100,
      gold: 4000,
      type: "boss",
      mat: "cursed_skull",
    },

    // Desert
    sandworm: {
      name: "沙蟲",
      icon: "🐛",
      baseHp: 600,
      baseAtk: 100,
      speed: 60,
      gold: 100,
      type: "common",
      mat: "sunstone",
    },
    scorpion: {
      name: "巨蠍",
      icon: "🦂",
      baseHp: 300,
      baseAtk: 120,
      speed: 110,
      gold: 120,
      type: "elite",
      mat: "sunstone",
    },
    mummy: {
      name: "木乃伊",
      icon: "🤕",
      baseHp: 800,
      baseAtk: 80,
      speed: 50,
      gold: 110,
      type: "common",
      mat: "cloth",
    },
    sphinx: {
      name: "斯芬克斯",
      icon: "🦁",
      baseHp: 8000,
      baseAtk: 400,
      speed: 120,
      gold: 5000,
      type: "boss",
      mat: "mirage_sand",
    },

    // Abyss / Void
    void_walker: {
      name: "虛空行者",
      icon: "👤",
      baseHp: 50000,
      baseAtk: 2000,
      speed: 150,
      gold: 1000,
      type: "common",
      mat: "void_dust",
    },
    entropy_avatar: {
      name: "熵之化身",
      icon: "🌀",
      baseHp: 80000,
      baseAtk: 3000,
      speed: 80,
      gold: 1500,
      type: "elite",
      mat: "void_metal",
    },
    forgotten_god: {
      name: "被遺忘者",
      icon: "👁️",
      baseHp: 40000,
      baseAtk: 4000,
      speed: 200,
      gold: 2000,
      type: "elite",
      mat: "void_essence",
    },
    azathoth: {
      name: "阿撒托斯",
      icon: "🌌",
      baseHp: 500000,
      baseAtk: 10000,
      speed: 180,
      gold: 50000,
      type: "boss",
      mat: "void_soul",
    },
  },
  specialItems: {
    soul_anchor: {
      name: "靈魂定錨",
      type: "material",
      rarity: "legendary",
      desc: "保留種族職業至下周目。",
      value: 0,
      icon: "⚓",
    },
  },
  events: [
    { id: "gambler", name: "瘋狂賭徒", icon: "🎲", weight: 8 },
    { id: "cursed_sword", name: "詛咒之劍", icon: "🗡️", weight: 5 },
    { id: "alchemist", name: "煉金術師", icon: "🧪", weight: 8 },
    { id: "spring", name: "治癒之泉", icon: "⛲", weight: 15 },
    { id: "trap", name: "陷阱", icon: "🪤", weight: 10 },
    { id: "chest", name: "寶箱", icon: "📦", weight: 20 },
    { id: "demon_whisper", name: "古神低語", icon: "🐙", weight: 5 }, // Renamed
    { id: "black_market", name: "黑市商人", icon: "🕵️", weight: 8 },
  ],
  itemPool: {
    common: [
      { name: "鐵劍", type: "weapon", baseAtk: 5 },
      { name: "皮甲", type: "armor_upper", baseHp: 20 },
      { name: "皮靴", type: "armor_lower", baseSpd: 5 },
    ],
    sets: {
      adventurer: [
        { name: "冒險者劍", type: "weapon", baseAtk: 8 },
        { name: "冒險者衣", type: "armor_upper", baseHp: 30 },
        { name: "冒險者靴", type: "armor_lower", baseSpd: 8 },
      ],
      forest: [
        { name: "精靈弓", type: "weapon", baseAtk: 12 },
        { name: "藤蔓甲", type: "armor_upper", baseHp: 50 },
        { name: "草鞋", type: "armor_lower", baseSpd: 12 },
      ],
      miner: [
        { name: "礦鎬", type: "weapon", baseAtk: 15 },
        { name: "鐵板甲", type: "armor_upper", baseHp: 80 },
        { name: "鐵護膝", type: "armor_lower", baseSpd: -5 },
      ],
      flame: [
        { name: "炎劍", type: "weapon", baseAtk: 20 },
        { name: "熔岩甲", type: "armor_upper", baseHp: 80 },
        { name: "烈焰靴", type: "armor_lower", baseHp: 40 },
      ],
      glacial: [
        { name: "冰刺劍", type: "weapon", baseAtk: 30 },
        { name: "寒冰甲", type: "armor_upper", baseHp: 120 },
        { name: "雪地靴", type: "armor_lower", baseHp: 50, baseSpd: -5 },
      ],
      necro: [
        { name: "骨劍", type: "weapon", baseAtk: 40 },
        { name: "屍布", type: "armor_upper", baseHp: 80, baseSpd: 5 },
        { name: "幽靈行者", type: "armor_lower", baseSpd: 15 },
      ],
      sandstorm: [
        { name: "蠍刺匕首", type: "weapon", baseAtk: 35, baseSpd: 10 },
        { name: "沙漠風衣", type: "armor_upper", baseHp: 100, baseSpd: 5 },
        { name: "流沙靴", type: "armor_lower", baseSpd: 20 },
      ],
      wolf_pack: [], // Only accessories for now
      slime_kin: [],
      goblin_horde: [],
      void: [
        // Unique Mythic Names
        { name: "朗基努斯之槍", type: "weapon", baseAtk: 1000 },
        { name: "埃癸斯之盾", type: "armor_upper", baseHp: 10000 },
        { name: "赫爾墨斯之靴", type: "armor_lower", baseSpd: 100 },
      ],
    },
  },
  sets: {
    adventurer: {
      name: "冒險者",
      bonus2: { maxHp: 20 },
      bonus4: { speed: 10 },
      bonus6: { all_stats: 0.1 },
    },
    forest: {
      name: "森之靈",
      bonus2: { hp_regen: 5 },
      bonus4: { dodge: 0.1 },
      bonus6: { hp_regen: 20, speed: 20 },
    },
    miner: {
      name: "礦工",
      bonus2: { maxHp: 50 },
      bonus4: { block: 0.1 },
      bonus6: { def: 0.2, block: 0.1 },
    },
    flame: {
      name: "火焰行者",
      bonus2: { atk_pct: 0.1 },
      bonus4: { atk: 20 },
      bonus6: { true_dmg: 30 },
    },
    glacial: {
      name: "冰川之壁",
      bonus2: { maxHp: 100 },
      bonus4: { block: 0.15 },
      bonus6: { reflect: 0.3 },
    },
    necro: {
      name: "死靈法師",
      bonus2: { lifesteal: 0.03 },
      bonus4: { atk: 30 },
      bonus6: { lifesteal: 0.1 },
    },
    sandstorm: {
      name: "沙暴行者",
      bonus2: { speed: 15 },
      bonus4: { dodge: 0.12 },
      bonus6: { extra_turn: 0.1 },
    },
    wolf_pack: {
      name: "狼群之心",
      bonus2: { speed: 15 },
      bonus4: { crit: 0.1 },
      bonus6: { crit_dmg: 0.5 },
    },
    slime_kin: {
      name: "凝膠共生",
      bonus2: { maxHp: 80 },
      bonus4: { hp_regen: 10 },
      bonus6: { damage_reduce: 0.15 },
    },
    goblin_horde: {
      name: "哥布林眾",
      bonus2: { gold: 0.2 }, // gold gain
      bonus4: { speed: 20 },
      bonus6: { multi_hit_chance: 0.25 },
    },
    void: {
      name: "虛空主宰",
      bonus2: { all_stats: 0.5 },
      bonus4: { true_dmg: 500 },
      bonus6: { extra_turn: 0.3 },
    },
  },
  materials: {
    slime_gel: { name: "凝膠", value: 5 },
    wolf_fang: { name: "狼牙", value: 15 },
    bat_wing: { name: "蝠翼", value: 12 },
    cloth: { name: "破布", value: 10 },
    ancient_wood: { name: "古木", value: 100 },
    iron_ore: { name: "鐵礦", value: 20 },
    fire_essence: { name: "火精", value: 50 },
    hell_leather: { name: "地獄皮", value: 80 },
    permafrost: { name: "永凍冰晶", value: 120 },
    soul_dust: { name: "靈魂粉末", value: 150 },
    sunstone: { name: "太陽石", value: 200 },
    magic_dust: { name: "魔法粉塵", value: 1 },
    // Boss Drops
    wind_crest: { name: "風之紋章", value: 500 },
    life_seed: { name: "生命種子", value: 800 },
    earth_shard: { name: "大地碎片", value: 1000 },
    eternal_ember: { name: "永燃餘燼", value: 1500 },
    frozen_heart: { name: "冰霜之心", value: 2000 },
    cursed_skull: { name: "詛咒頭骨", value: 2500 },
    mirage_sand: { name: "幻象之沙", value: 3000 },
    // Abyss Materials
    void_dust: { name: "星之彩", value: 5000 },
    void_metal: { name: "奧利哈鋼", value: 8000 },
    void_essence: { name: "以太精華", value: 10000 },
    void_soul: { name: "神性殘渣", value: 50000 },
  },
  recipes: [
    // Adventurer / Basic
    {
      name: "狼牙項鍊",
      type: "accessory",
      stats: { atk: 5, crit: 0.05 },
      req: { wolf_fang: 5 },
      setId: "adventurer",
    },
    {
      name: "聲波耳環",
      type: "accessory",
      stats: { speed: 5 },
      req: { bat_wing: 5 },
      setId: "adventurer",
    },
    {
      name: "小偷手套",
      type: "accessory",
      stats: { speed: 5, gold: 5 },
      req: { cloth: 5 },
      setId: "goblin_horde",
    },

    // Slime
    {
      name: "凝膠戒指",
      type: "accessory",
      stats: { maxHp: 30 },
      req: { slime_gel: 5 },
      setId: "slime_kin",
    },
    {
      name: "粘液護符",
      type: "accessory",
      stats: { maxHp: 50, hp_regen: 2 },
      req: { slime_gel: 10, cloth: 2 },
      setId: "slime_kin",
    },

    // Wolf
    {
      name: "恐狼紋章",
      type: "accessory",
      stats: { atk: 15, speed: 10 },
      req: { wolf_fang: 10, iron_ore: 1 },
      setId: "wolf_pack",
    },
    {
      name: "狼王之冠",
      type: "accessory",
      stats: { atk: 30, crit: 0.1 },
      req: { wolf_fang: 20, gold: 500 },
      setId: "wolf_pack",
    },

    // Forest
    {
      name: "自然護符",
      type: "accessory",
      stats: { maxHp: 50 },
      req: { slime_gel: 5, ancient_wood: 1 },
      setId: "forest",
    },
    {
      name: "樹精核心",
      type: "accessory",
      stats: { maxHp: 100, hp_regen: 5 },
      req: { ancient_wood: 5 },
      setId: "forest",
    },

    // Miner
    {
      name: "礦工護目鏡",
      type: "accessory",
      stats: { maxHp: 40, crit: 0.05 },
      req: { iron_ore: 5 },
      setId: "miner",
    },
    {
      name: "岩石之心",
      type: "accessory",
      stats: { maxHp: 150, block: 0.05 },
      req: { iron_ore: 10, permafrost: 1 },
      setId: "miner",
    },

    // Flame
    {
      name: "火焰戒指",
      type: "accessory",
      stats: { atk: 10 },
      req: { fire_essence: 2 },
      setId: "flame",
    },
    {
      name: "惡魔之角",
      type: "accessory",
      stats: { atk: 25, crit: 0.05 },
      req: { fire_essence: 5, hell_leather: 2 },
      setId: "flame",
    },

    // Tundra
    {
      name: "冰霜護符",
      type: "accessory",
      stats: { block: 0.05, maxHp: 80 },
      req: { permafrost: 3, iron_ore: 2 },
      setId: "glacial",
    },
    {
      name: "雪怪皮帶",
      type: "accessory",
      stats: { maxHp: 120, def: 5 },
      req: { permafrost: 5, hell_leather: 1 },
      setId: "glacial",
    },

    // Graveyard
    {
      name: "亡者之戒",
      type: "accessory",
      stats: { lifesteal: 0.02, atk: 10 },
      req: { soul_dust: 3, cloth: 5 },
      setId: "necro",
    },
    {
      name: "吸血鬼披風",
      type: "accessory",
      stats: { lifesteal: 0.05, speed: 10 },
      req: { bat_wing: 10, soul_dust: 5 },
      setId: "necro",
    },

    // Desert
    {
      name: "沙漠之眼",
      type: "accessory",
      stats: { dodge: 0.05, speed: 10 },
      req: { sunstone: 3, gold: 500 },
      setId: "sandstorm",
    },
    {
      name: "法老面具",
      type: "accessory",
      stats: { maxHp: 200, dodge: 0.05 },
      req: { sunstone: 10, cloth: 10 },
      setId: "sandstorm",
    },

    // Key
    {
      name: "幻界之鑰",
      type: "consumable",
      effect: { open_world: "phantasm" },
      desc: "開啟通往幻夢境的大門",
      req: {
        wind_crest: 1,
        life_seed: 1,
        earth_shard: 1,
        eternal_ember: 1,
        frozen_heart: 1,
        cursed_skull: 1,
        mirage_sand: 1,
      },
      setId: "adventurer", // Dummy set
    },
  ],
  rarity: {
    common: {
      name: "普通",
      color: "text-common",
      border: "border-common",
      mult: 1.0,
      affixMult: 1.0,
      chance: 0.6,
      minDepth: 0,
    },
    uncommon: {
      name: "優良",
      color: "text-uncommon",
      border: "border-uncommon",
      mult: 1.2,
      affixMult: 1.5,
      chance: 0.25,
      minDepth: 0,
    },
    rare: {
      name: "稀有",
      color: "text-rare",
      border: "border-rare",
      mult: 1.5,
      affixMult: 2.0,
      chance: 0.1,
      minDepth: 10,
    },
    epic: {
      name: "史詩",
      color: "text-epic",
      border: "border-epic",
      mult: 2.0,
      affixMult: 3.0,
      chance: 0.04,
      minDepth: 30,
    },
    legendary: {
      name: "傳說",
      color: "text-legendary",
      border: "border-legendary",
      mult: 3.0,
      affixMult: 5.0,
      chance: 0.01,
      minDepth: 60,
    },
    abyssal: {
      name: "深淵",
      color: "text-abyssal", // Need CSS
      border: "border-abyssal", // Need CSS
      mult: 20.0, // Insane multiplier
      affixMult: 10.0,
      chance: 0.005, // Very rare, but guaranteed in abyss via ItemSystem
      minDepth: 500,
    },
  },
  affixes: {
    prefixes: [
      { name: "鋒利", type: "atk", val: 0.05 },
      { name: "堅固", type: "maxHp", val: 0.05 },
      { name: "輕盈", type: "speed", val: 0.05 },
      { name: "蠻牛", type: "maxHp", val: 0.1, minRarity: "rare" },
      { name: "致命", type: "atk", val: 0.1, minRarity: "rare" },
      { name: "殘暴", type: "crit", val: 0.05, minRarity: "uncommon" },
      { name: "鐵壁", type: "block", val: 0.05, minRarity: "rare" },
      { name: "疾風", type: "speed", val: 0.1, minRarity: "rare" },
      { name: "巨神", type: "maxHp", val: 0.15, minRarity: "epic" },
      { name: "毀滅", type: "atk", val: 0.15, minRarity: "epic" },
    ],
    suffixes: [
      { name: "熊", type: "flat_hp", val: 15 },
      { name: "狼", type: "flat_atk", val: 4 },
      { name: "鷹", type: "flat_spd", val: 6 },
      { name: "吸血", type: "lifesteal", val: 0.02, minRarity: "rare" },
      { name: "再生", type: "hp_regen", val: 4, minRarity: "uncommon" },
      { name: "破壞", type: "flat_atk", val: 10, minRarity: "rare" },
      { name: "守護", type: "flat_hp", val: 50, minRarity: "rare" },
      { name: "迅捷", type: "flat_spd", val: 15, minRarity: "rare" },
      { name: "壁壘", type: "block", val: 0.05, minRarity: "epic" },
    ],
  },
};
