const CONFIG = {
  // =========================================
  // 1. 種族設定 (Races)
  // =========================================
  races: {
    // --- 基礎種族 ---
    human: {
      name: "人類",
      desc: "適應力強，學習能力快，各項能力平均。",
      mod: { maxHp: 1.0, atk: 1.0, speed: 1.0, exp: 1.1 },
    },
    elf: {
      name: "精靈",
      desc: "森林的子民，身手矯健，擅長閃避。",
      mod: { maxHp: 0.85, atk: 1.05, speed: 1.25 },
    },
    orc: {
      name: "獸人",
      desc: "充滿野性的戰鬥種族，攻擊力驚人。",
      mod: { maxHp: 1.2, atk: 1.2, speed: 0.9 },
    },
    dwarf: {
      name: "矮人",
      desc: "如岩石般堅硬，生命力與負重能力頑強。",
      mod: { maxHp: 1.3, atk: 0.95, speed: 0.8 },
    },
    halfling: {
      name: "半身人",
      desc: "體型嬌小但極其幸運，容易發現寶物。",
      mod: { maxHp: 0.8, atk: 0.9, speed: 1.15 },
    },

    // --- 條件解鎖種族 ---
    undead: {
      name: "亡靈",
      desc: "[隱藏] 非生者，免疫毒素但無法使用藥水恢復。",
      hidden: true,
      mod: { maxHp: 0.7, atk: 1.4, speed: 0.9 },
    },
    dragonkin: {
      name: "龍人",
      desc: "[隱藏] 擁有龍之血脈，攻守兼備的強大戰士。",
      hidden: true,
      mod: { maxHp: 1.2, atk: 1.2, speed: 1.0 },
    },

    // --- 後期特殊種族 ---
    demon_spawn: {
      name: "魔人",
      desc: "[煉獄專屬] 與惡魔融合，以業力為食，越戰越強。",
      hidden: true,
      mod: { maxHp: 1.5, atk: 1.5, speed: 1.1 },
    },
    void_walker: {
      name: "虛空行者",
      desc: "[幻界專屬] 沒有實體，理智值消耗減半，極度敏捷。",
      hidden: true,
      mod: { maxHp: 0.8, atk: 1.3, speed: 1.4 },
    },
  },

  // =========================================
  // 2. 職業設定 (Classes)
  // =========================================
  classes: {
    // --- T1 基礎職業 ---
    warrior: {
      name: "戰士",
      desc: "精通近戰武器，攻守兼備。",
      bonus: { maxHp: 20, atk: 5 },
      style: "standard",
      promotesTo: "knight",
      preferred: ["sword", "axe", "mace"],
    },
    thief: {
      name: "盜賊",
      desc: "身手敏捷，擅長偷襲與暴擊。",
      bonus: { speed: 15, crit: 0.1 },
      style: "multi_hit",
      hits: 2,
      promotesTo: "assassin",
      preferred: ["dagger"],
    },
    archer: {
      name: "弓手",
      desc: "遠程狙擊，先發制人。",
      bonus: { speed: 10, atk: 8 },
      style: "preemptive",
      promotesTo: "ranger",
      preferred: ["bow"],
    },
    mage: {
      name: "法師",
      desc: "掌控元素，攻擊無法被閃避。",
      bonus: { atk: 15, maxHp: -10 },
      style: "true_strike",
      promotesTo: "archmage",
      preferred: ["staff"],
    },
    cleric: {
      name: "牧師",
      desc: "受到神之加護，自我恢復能力強。",
      bonus: { maxHp: 30, def: 0.1 },
      style: "regen",
      promotesTo: "paladin",
      preferred: ["mace", "staff"],
    },

    // --- T2 進階職業 ---
    knight: {
      name: "皇家騎士",
      desc: "銅牆鐵壁，擅長格擋反擊。",
      bonus: { maxHp: 100, def: 0.2 },
      style: "counter_attack",
      preferred: ["sword", "mace"],
    },
    assassin: {
      name: "暗影刺客",
      desc: "陰影中的死神，追求極致暴擊。",
      bonus: { atk: 30, crit: 0.3 },
      style: "execute",
      preferred: ["dagger"],
    },
    ranger: {
      name: "叢林遊俠",
      desc: "箭無虛發，連續射擊。",
      bonus: { speed: 25, atk: 15 },
      style: "stun_shot",
      preferred: ["bow"],
    },
    archmage: {
      name: "大魔導士",
      desc: "毀滅魔法的化身，雙重詠唱。",
      bonus: { atk: 50, speed: 5 },
      style: "double_cast",
      preferred: ["staff"],
    },
    paladin: {
      name: "聖騎士",
      desc: "聖光守護，愈戰愈強。",
      bonus: { maxHp: 150, hp_regen: 10 },
      style: "scaling_atk",
      preferred: ["mace", "sword"],
    },

    // --- 特殊條件解鎖職業 ---
    berserker: {
      name: "狂戰士",
      desc: "[隱藏] 血量越低攻擊越高，放棄防禦。",
      hidden: true,
      bonus: { atk: 20, maxHp: 50 },
      style: "blood_rage",
      unlockCheck: (p) => p.currentHp / p.stats.maxHp < 0.05,
      preferred: ["axe"],
    },
    merchant: {
      name: "豪商",
      desc: "[隱藏] 金錢就是力量，能用錢解決戰鬥。",
      hidden: true,
      bonus: { gold_drop: 0.5 },
      style: "money_power",
      unlockCheck: (p) => p.gold >= 3000,
      preferred: ["dagger", "staff"],
    },
    gambler: {
      name: "賭徒",
      desc: "[隱藏] 運氣決定一切，傷害浮動巨大。",
      hidden: true,
      bonus: { crit: 0.5, dodge: -9.0 },
      style: "roulette",
      unlockCheck: (p) => false, // 暫定只能透過事件轉職
      preferred: ["dagger"],
    },

    // --- 後期專屬職業 ---
    hell_knight: {
      name: "地獄騎士",
      desc: "[煉獄] 燃燒靈魂，將業力轉化為真實傷害。",
      hidden: true,
      bonus: { atk: 80, def: 0.1 },
      style: "karma_strike",
      preferred: ["sword", "axe"],
    },
    dream_weaver: {
      name: "織夢者",
      desc: "[幻界] 操縱理智，使現實扭曲。",
      hidden: true,
      bonus: { speed: 40, atk: 40 },
      style: "sanity_control",
      preferred: ["staff", "bow"],
    },
  },

  // =========================================
  // 3. 區域與生物群系 (Biomes)
  // =========================================
  biomes: {
    plains: {
      name: "新手平原",
      icon: "🌱",
      color: "#8bc34a",
      minDepth: 0,
      scaling: 1.0,
      set: "adventurer",
      desc: "風和日麗的草原，適合新手冒險者試煉身手。",
      monsters: ["slime", "wolf", "bat", "rat"],
      elites: ["wolf_king", "giant_slime"],
      boss: "gnoll_king",
    },
    forest: {
      name: "迷霧森林",
      icon: "🌲",
      color: "#2e7d32",
      minDepth: 20,
      scaling: 1.5,
      set: "forest",
      desc: "陽光難以穿透的茂密森林，深處傳來詭異的聲響。",
      monsters: ["forest_wolf", "goblin", "spider", "forest_slime"],
      elites: ["ent", "goblin_chief"],
      boss: "ancient_treant",
    },
    cave: {
      name: "深淵礦坑",
      icon: "⛏️",
      color: "#795548",
      minDepth: 50,
      scaling: 2.5,
      set: "miner",
      desc: "陰暗潮濕的地下坑道，迴盪著金屬敲擊的回音。",
      monsters: ["cave_bat", "rock_worm", "skeleton", "kobold"],
      elites: ["rock_golem", "skeleton_captain"],
      boss: "troll_warlord",
    },
    volcano: {
      name: "焦熱地獄",
      icon: "🌋",
      color: "#d32f2f",
      minDepth: 100,
      scaling: 4.0,
      set: "flame",
      desc: "空氣中充滿硫磺味，地面流淌著致命的岩漿。",
      monsters: ["fire_slime", "hell_hound", "imp", "lava_golem"],
      elites: ["fire_elemental", "cerberus"],
      boss: "red_dragon",
    },
    tundra: {
      name: "凜冬雪原",
      icon: "❄️",
      color: "#4fc3f7",
      minDepth: 150,
      scaling: 6.0,
      set: "glacial",
      desc: "暴風雪肆虐的極寒之地，只有最強壯的生物能存活。",
      monsters: ["ice_wolf", "snow_bat", "yeti", "ice_elemental"],
      elites: ["ice_golem", "white_walker"],
      boss: "frost_giant",
    },
    graveyard: {
      name: "幽暗墓地",
      icon: "🪦",
      color: "#9e9e9e",
      minDepth: 200,
      scaling: 9.0,
      set: "necro",
      desc: "亡者的安息之地，如今卻充滿了不安的靈魂。",
      monsters: ["zombie", "ghost", "skeleton_mage", "ghoul"],
      elites: ["death_knight", "wraith"],
      boss: "lich_king",
    },
    desert: {
      name: "炙熱沙漠",
      icon: "🏜️",
      color: "#ffb74d",
      minDepth: 250,
      scaling: 12.0,
      set: "sandstorm",
      desc: "無盡的黃沙與烈日，埋葬了無數迷途的旅人。",
      monsters: ["sand_worm", "desert_wolf", "mummy", "scorpion"],
      elites: ["scorpion_king", "sphinx_guard"],
      boss: "anubis_avatar",
    },

    // --- 後期區域 ---
    purgatory: {
      name: "無間煉獄",
      icon: "🔥",
      color: "#b71c1c",
      minDepth: 9999,
      scaling: 50.0,
      set: "sin",
      desc: "生者禁入的流放之地。這裡沒有希望，只有無盡的刑罰與罪孽。惡魔領主注視著你。",
      monsters: ["tortured_soul", "demon_soldier", "hell_beast", "succubus"],
      elites: ["fallen_angel", "sin_eater"],
      boss: "lucifer_avatar",
    },
    phantasm: {
      name: "幻夢境",
      icon: "🌀",
      color: "#6a1b9a",
      minDepth: 9999,
      scaling: 30.0,
      set: "void",
      desc: "現實與夢境的夾縫，幾何結構在這裡毫無意義。理智是你唯一的護盾，小心發瘋。",
      monsters: ["tentacle_horror", "star_spawn", "mind_flayer", "night_gaunt"],
      elites: ["shoggoth", "deep_one"],
      boss: "cthulhu_avatar",
    },
  },

  // =========================================
  // 4. 怪物詳細資料 (Monsters)
  // =========================================
  monsters: {
    // --- 平原系 ---
    slime: {
      name: "史萊姆",
      icon: "💧",
      species: "slime",
      type: "common",
      baseHp: 30,
      baseAtk: 5,
      speed: 50,
      gold: 5,
      mat: "slime_gel",
      desc: "最弱小的凝膠生物。",
    },
    rat: {
      name: "巨鼠",
      icon: "🐀",
      species: "beast",
      type: "common",
      baseHp: 25,
      baseAtk: 8,
      speed: 110,
      gold: 6,
      mat: "fur",
      desc: "眼睛發紅的巨大老鼠。",
    },
    bat: {
      name: "吸血蝠",
      icon: "🦇",
      species: "beast",
      type: "common",
      baseHp: 20,
      baseAtk: 10,
      speed: 120,
      gold: 7,
      mat: "bat_wing",
      desc: "喜歡躲在陰影中襲擊。",
    },
    wolf: {
      name: "野狼",
      icon: "🐺",
      species: "wolf",
      type: "common",
      baseHp: 50,
      baseAtk: 12,
      speed: 100,
      gold: 8,
      mat: "wolf_fang",
      desc: "成群結隊的獵食者。",
    },

    // --- 森林系 ---
    forest_wolf: {
      name: "恐狼",
      icon: "🐺",
      species: "wolf",
      type: "common",
      baseHp: 120,
      baseAtk: 30,
      speed: 110,
      gold: 20,
      mat: "wolf_fang",
      desc: "比普通狼更大更兇猛。",
    },
    spider: {
      name: "巨型蜘蛛",
      icon: "🕷️",
      species: "insect",
      type: "common",
      baseHp: 90,
      baseAtk: 25,
      speed: 95,
      gold: 18,
      mat: "spider_silk",
      desc: "帶有劇毒的獠牙。",
    },
    goblin: {
      name: "哥布林",
      icon: "👺",
      species: "humanoid",
      type: "common",
      baseHp: 80,
      baseAtk: 20,
      speed: 105,
      gold: 25,
      mat: "cloth",
      desc: "狡猾的亞人種族。",
    },
    forest_slime: {
      name: "苔蘚史萊姆",
      icon: "🦠",
      species: "slime",
      type: "common",
      baseHp: 150,
      baseAtk: 15,
      speed: 60,
      gold: 15,
      mat: "slime_gel",
      desc: "混入了森林毒素。",
    },

    // --- 洞穴系 ---
    cave_bat: {
      name: "暗影巨蝠",
      icon: "🦇",
      species: "beast",
      type: "common",
      baseHp: 200,
      baseAtk: 50,
      speed: 130,
      gold: 35,
      mat: "bat_wing",
      desc: "適應了完全黑暗的環境。",
    },
    rock_worm: {
      name: "岩石蠕蟲",
      icon: "🪱",
      species: "insect",
      type: "common",
      baseHp: 400,
      baseAtk: 60,
      speed: 40,
      gold: 40,
      mat: "iron_ore",
      desc: "能嚼碎石頭的口器。",
    },
    kobold: {
      name: "狗頭人礦工",
      icon: "🐕",
      species: "humanoid",
      type: "common",
      baseHp: 250,
      baseAtk: 45,
      speed: 90,
      gold: 50,
      mat: "iron_ore",
      desc: "守護著它們的礦脈。",
    },

    // --- 火山系 ---
    fire_slime: {
      name: "岩漿史萊姆",
      icon: "🔥",
      species: "slime",
      type: "common",
      baseHp: 500,
      baseAtk: 80,
      speed: 70,
      gold: 60,
      mat: "fire_essence",
      desc: "體內燃燒著烈火。",
    },
    hell_hound: {
      name: "地獄犬",
      icon: "🐕",
      species: "beast",
      type: "common",
      baseHp: 600,
      baseAtk: 100,
      speed: 120,
      gold: 80,
      mat: "hell_leather",
      desc: "來自地獄的看門狗。",
    },
    imp: {
      name: "小惡魔",
      icon: "👿",
      species: "demon",
      type: "common",
      baseHp: 450,
      baseAtk: 120,
      speed: 140,
      gold: 70,
      mat: "fire_essence",
      desc: "喜歡惡作劇的低階惡魔。",
    },
    lava_golem: {
      name: "熔岩傀儡",
      icon: "🗿",
      species: "construct",
      type: "common",
      baseHp: 1000,
      baseAtk: 150,
      speed: 30,
      gold: 100,
      mat: "iron_ore",
      desc: "流淌著岩漿的石頭人。",
    },

    // --- 雪原系 ---
    ice_wolf: {
      name: "冰原狼",
      icon: "❄️",
      species: "wolf",
      type: "common",
      baseHp: 800,
      baseAtk: 120,
      speed: 130,
      gold: 90,
      mat: "permafrost",
      desc: "毛皮如鋼鐵般堅硬。",
    },
    snow_bat: {
      name: "白翼蝠",
      icon: "🕊️",
      species: "beast",
      type: "common",
      baseHp: 600,
      baseAtk: 100,
      speed: 150,
      gold: 80,
      mat: "permafrost",
      desc: "與風雪融為一體。",
    },
    yeti: {
      name: "雪怪",
      icon: "🦍",
      species: "beast",
      type: "common",
      baseHp: 1500,
      baseAtk: 200,
      speed: 60,
      gold: 120,
      mat: "fur",
      desc: "擁有驚人怪力的巨獸。",
    },
    ice_elemental: {
      name: "冰元素",
      icon: "🧊",
      species: "elemental",
      type: "common",
      baseHp: 900,
      baseAtk: 150,
      speed: 90,
      gold: 100,
      mat: "permafrost",
      desc: "純粹的寒冰魔力集合體。",
    },

    // --- 墓地系 ---
    zombie: {
      name: "腐屍",
      icon: "🧟",
      species: "undead",
      type: "common",
      baseHp: 2000,
      baseAtk: 150,
      speed: 50,
      gold: 100,
      mat: "cloth",
      desc: "散發著惡臭，生命力頑強。",
    },
    skeleton: {
      name: "骷髏兵",
      icon: "💀",
      species: "undead",
      type: "common",
      baseHp: 1200,
      baseAtk: 180,
      speed: 80,
      gold: 90,
      mat: "soul_dust",
      desc: "動作僵硬但不知疲倦。",
    },
    skeleton_mage: {
      name: "骷髏法師",
      icon: "🧙",
      species: "undead",
      type: "common",
      baseHp: 800,
      baseAtk: 300,
      speed: 70,
      gold: 150,
      mat: "soul_dust",
      desc: "掌握了黑暗魔法。",
    },
    ghoul: {
      name: "食屍鬼",
      icon: "👹",
      species: "undead",
      type: "common",
      baseHp: 1500,
      baseAtk: 200,
      speed: 110,
      gold: 130,
      mat: "soul_dust",
      desc: "渴望新鮮血肉。",
    },

    // --- 沙漠系 ---
    sand_worm: {
      name: "巨型沙蟲",
      icon: "🐛",
      species: "beast",
      type: "common",
      baseHp: 3000,
      baseAtk: 250,
      speed: 60,
      gold: 180,
      mat: "sunstone",
      desc: "潛伏在沙地下的吞噬者。",
    },
    desert_wolf: {
      name: "沙狼",
      icon: "🐕",
      species: "wolf",
      type: "common",
      baseHp: 2000,
      baseAtk: 220,
      speed: 140,
      gold: 160,
      mat: "sunstone",
      desc: "擅長在沙暴中隱藏身形。",
    },
    mummy: {
      name: "木乃伊",
      icon: "🤕",
      species: "undead",
      type: "common",
      baseHp: 2500,
      baseAtk: 200,
      speed: 50,
      gold: 200,
      mat: "cloth",
      desc: "受詛咒的古代屍體。",
    },
    scorpion: {
      name: "劇毒蠍",
      icon: "🦂",
      species: "insect",
      type: "common",
      baseHp: 1800,
      baseAtk: 300,
      speed: 100,
      gold: 150,
      mat: "sunstone",
      desc: "尾針帶有致命毒素。",
    },

    // --- 菁英怪 (Elites) ---
    wolf_king: {
      name: "狼王",
      icon: "👑",
      species: "wolf",
      type: "elite",
      baseHp: 500,
      baseAtk: 60,
      speed: 120,
      gold: 150,
      mat: "wolf_fang",
      desc: "統領狼群的王者，氣場逼人。",
    },
    giant_slime: {
      name: "巨型史萊姆",
      icon: "🔵",
      species: "slime",
      type: "elite",
      baseHp: 800,
      baseAtk: 50,
      speed: 40,
      gold: 120,
      mat: "slime_gel",
      desc: "吞噬了無數同類而變得巨大的個體。",
    },
    ent: {
      name: "樹人守衛",
      icon: "🌳",
      species: "plant",
      type: "elite",
      baseHp: 2500,
      baseAtk: 150,
      speed: 40,
      gold: 300,
      mat: "ancient_wood",
      desc: "森林的憤怒化身。",
    },
    goblin_chief: {
      name: "哥布林酋長",
      icon: "👺",
      species: "humanoid",
      type: "elite",
      baseHp: 2000,
      baseAtk: 120,
      speed: 110,
      gold: 250,
      mat: "cloth",
      desc: "狡猾且裝備精良。",
    },
    rock_golem: {
      name: "岩石巨兵",
      icon: "🗿",
      species: "construct",
      type: "elite",
      baseHp: 4000,
      baseAtk: 200,
      speed: 30,
      gold: 400,
      mat: "iron_ore",
      desc: "擁有驚人防禦力的魔法生物。",
    },
    skeleton_captain: {
      name: "骷髏隊長",
      icon: "💂",
      species: "undead",
      type: "elite",
      baseHp: 3000,
      baseAtk: 250,
      speed: 90,
      gold: 350,
      mat: "soul_dust",
      desc: "生前是精銳戰士。",
    },
    fire_elemental: {
      name: "火元素",
      icon: "🔥",
      species: "elemental",
      type: "elite",
      baseHp: 5000,
      baseAtk: 400,
      speed: 100,
      gold: 600,
      mat: "fire_essence",
      desc: "純粹的毀滅火焰。",
    },
    cerberus: {
      name: "地獄三頭犬",
      icon: "🐕‍🦺",
      species: "wolf",
      type: "elite",
      baseHp: 6000,
      baseAtk: 450,
      speed: 110,
      gold: 700,
      mat: "hell_leather",
      desc: "看守地獄之門的惡犬。",
    },
    ice_golem: {
      name: "寒冰魔像",
      icon: "☃️",
      species: "construct",
      type: "elite",
      baseHp: 8000,
      baseAtk: 500,
      speed: 40,
      gold: 800,
      mat: "permafrost",
      desc: "由永凍冰構成的無情守衛。",
    },
    white_walker: {
      name: "白鬼",
      icon: "👻",
      species: "undead",
      type: "elite",
      baseHp: 7000,
      baseAtk: 600,
      speed: 130,
      gold: 900,
      mat: "soul_dust",
      desc: "遊蕩在暴風雪中的亡魂。",
    },
    death_knight: {
      name: "死亡騎士",
      icon: "🏇",
      species: "undead",
      type: "elite",
      baseHp: 10000,
      baseAtk: 700,
      speed: 100,
      gold: 1200,
      mat: "soul_dust",
      desc: "騎著骸骨戰馬的恐怖騎士。",
    },
    wraith: {
      name: "怨靈",
      icon: "🌫️",
      species: "undead",
      type: "elite",
      baseHp: 6000,
      baseAtk: 900,
      speed: 140,
      gold: 1000,
      mat: "soul_dust",
      desc: "物理攻擊對它效果不佳。",
    },
    scorpion_king: {
      name: "蠍子王",
      icon: "🦂",
      species: "insect",
      type: "elite",
      baseHp: 15000,
      baseAtk: 800,
      speed: 110,
      gold: 1500,
      mat: "sunstone",
      desc: "半人半蠍的沙漠暴君。",
    },
    sphinx_guard: {
      name: "斯芬克斯衛士",
      icon: "🦁",
      species: "construct",
      type: "elite",
      baseHp: 20000,
      baseAtk: 1000,
      speed: 80,
      gold: 2000,
      mat: "sunstone",
      desc: "守護古墓的石像。",
    },

    // === BOSS ===
    gnoll_king: {
      name: "豺狼人首領",
      icon: "🦁",
      type: "boss",
      baseHp: 2000,
      baseAtk: 100,
      speed: 90,
      gold: 500,
      mat: "wind_crest",
      desc: "統領平原的霸主，手持巨大的流星錘。",
    },
    ancient_treant: {
      name: "遠古樹精",
      icon: "🎄",
      type: "boss",
      baseHp: 8000,
      baseAtk: 300,
      speed: 50,
      gold: 1500,
      mat: "life_seed",
      desc: "活了上千年的森林守護者。",
    },
    troll_warlord: {
      name: "巨魔戰將",
      icon: "👹",
      type: "boss",
      baseHp: 15000,
      baseAtk: 500,
      speed: 70,
      gold: 3000,
      mat: "earth_shard",
      desc: "狂暴且嗜血的地下霸主。",
    },
    red_dragon: {
      name: "深淵紅龍",
      icon: "🐉",
      type: "boss",
      baseHp: 30000,
      baseAtk: 1000,
      speed: 100,
      gold: 8000,
      mat: "eternal_ember",
      desc: "火山的支配者，吐息能融化一切。",
    },
    frost_giant: {
      name: "冰霜巨人",
      icon: "🥶",
      type: "boss",
      baseHp: 40000,
      baseAtk: 1200,
      speed: 60,
      gold: 10000,
      mat: "frozen_heart",
      desc: "北方傳說中的巨人，每一步都引發地震。",
    },
    lich_king: {
      name: "不死巫妖",
      icon: "🧙",
      type: "boss",
      baseHp: 35000,
      baseAtk: 1500,
      speed: 110,
      gold: 15000,
      mat: "cursed_skull",
      desc: "掌握死亡奧秘的法師，擁有不死之身。",
    },
    anubis_avatar: {
      name: "阿努比斯化身",
      icon: "🐕",
      type: "boss",
      baseHp: 50000,
      baseAtk: 2000,
      speed: 130,
      gold: 20000,
      mat: "mirage_sand",
      desc: "沙漠中的死神化身，審判靈魂。",
    },

    // === 煉獄專屬 (Purgatory) ===
    tortured_soul: {
      name: "受折磨的靈魂",
      icon: "👻",
      species: "undead",
      type: "common",
      baseHp: 10000,
      baseAtk: 2000,
      speed: 90,
      gold: 500,
      mat: "sin_dust",
      desc: "發出淒厲慘叫的亡魂。",
    },
    demon_soldier: {
      name: "地獄魔兵",
      icon: "👺",
      species: "demon",
      type: "common",
      baseHp: 15000,
      baseAtk: 2500,
      speed: 110,
      gold: 800,
      mat: "demon_horn",
      desc: "穿著黑鐵盔甲的惡魔菁英。",
    },
    hell_beast: {
      name: "煉獄巨獸",
      icon: "🐗",
      species: "beast",
      type: "common",
      baseHp: 25000,
      baseAtk: 3000,
      speed: 80,
      gold: 1000,
      mat: "hell_leather",
      desc: "渾身燃燒著永不熄滅的業火。",
    },
    succubus: {
      name: "魅魔",
      icon: "💋",
      species: "demon",
      type: "common",
      baseHp: 12000,
      baseAtk: 3500,
      speed: 130,
      gold: 1200,
      mat: "demon_horn",
      desc: "誘惑並吞噬靈魂的惡魔。",
    },

    fallen_angel: {
      name: "墮落天使",
      icon: "🦇",
      species: "demon",
      type: "elite",
      baseHp: 100000,
      baseAtk: 8000,
      speed: 150,
      gold: 5000,
      mat: "black_feather",
      desc: "背叛了光明的戰士，擁有極高的戰鬥技巧。",
    },
    sin_eater: {
      name: "食罪者",
      icon: "👅",
      species: "demon",
      type: "elite",
      baseHp: 150000,
      baseAtk: 6000,
      speed: 60,
      gold: 8000,
      mat: "sin_dust",
      desc: "專門吞噬罪人的怪物。",
    },

    lucifer_avatar: {
      name: "路西法·傲慢化身",
      icon: "🌞",
      type: "boss",
      baseHp: 1000000,
      baseAtk: 20000,
      speed: 200,
      gold: 100000,
      mat: "pride_crown",
      desc: "【七宗罪】晨星之子，不可一世的傲慢魔王。",
    },
    lilith_avatar: {
      name: "莉莉絲·色慾化身",
      icon: "💄",
      type: "boss",
      baseHp: 800000,
      baseAtk: 25000,
      speed: 180,
      gold: 100000,
      mat: "pride_crown",
      desc: "【七宗罪】夜之魔女，所有慾望的源頭。",
    },
    mammon_avatar: {
      name: "瑪門·貪婪化身",
      icon: "💰",
      type: "boss",
      baseHp: 1200000,
      baseAtk: 15000,
      speed: 100,
      gold: 500000,
      mat: "pride_crown",
      desc: "【七宗罪】金錢的主宰，想要買下你的靈魂。",
    },

    // === 幻界專屬 (Phantasm) ===
    tentacle_horror: {
      name: "觸手恐怖",
      icon: "🦑",
      species: "aberration",
      type: "common",
      baseHp: 12000,
      baseAtk: 2200,
      speed: 100,
      gold: 600,
      mat: "void_slime",
      desc: "從虛空中伸出的滑膩觸手。",
    },
    star_spawn: {
      name: "星之眷族",
      icon: "👽",
      species: "aberration",
      type: "common",
      baseHp: 18000,
      baseAtk: 2800,
      speed: 130,
      gold: 900,
      mat: "star_dust",
      desc: "來自遙遠星空的異形生物。",
    },
    mind_flayer: {
      name: "奪心魔",
      icon: "🧠",
      species: "aberration",
      type: "common",
      baseHp: 15000,
      baseAtk: 3000,
      speed: 110,
      gold: 800,
      mat: "void_slime",
      desc: "會直接攻擊你的理智值。",
    },
    night_gaunt: {
      name: "夜魘",
      icon: "🌑",
      species: "aberration",
      type: "common",
      baseHp: 14000,
      baseAtk: 3200,
      speed: 160,
      gold: 1000,
      mat: "void_slime",
      desc: "沒有五官的黑色飛行生物。",
    },

    shoggoth: {
      name: "修格斯",
      icon: "⚫",
      species: "aberration",
      type: "elite",
      baseHp: 200000,
      baseAtk: 5000,
      speed: 50,
      gold: 6000,
      mat: "void_slime",
      desc: "不定形的肉塊，發出令人作嘔的聲音。",
    },
    deep_one: {
      name: "深潛者長老",
      icon: "🐟",
      species: "aberration",
      type: "elite",
      baseHp: 150000,
      baseAtk: 6000,
      speed: 140,
      gold: 8000,
      mat: "void_slime",
      desc: "古老海洋的統治者。",
    },

    cthulhu_avatar: {
      name: "克蘇魯·沉睡之神",
      icon: "🐙",
      type: "boss",
      baseHp: 2000000,
      baseAtk: 30000,
      speed: 100,
      gold: 200000,
      mat: "elder_sign",
      desc: "不可名狀的舊日支配者。直視祂將消耗大量理智。",
    },
  },

  // =========================================
  // 5. 物品與裝備池 (Items)
  // =========================================
  itemPool: {
    // 通用裝備
    common: [
      { name: "鐵劍", type: "weapon", subtype: "sword", baseAtk: 5 },
      { name: "皮甲", type: "armor_upper", baseHp: 20 },
      { name: "皮褲", type: "armor_lower", baseSpd: 5 },
      {
        name: "木盾",
        type: "weapon",
        subtype: "shield",
        baseHp: 30,
        baseDef: 0.05,
      },
      { name: "手斧", type: "weapon", subtype: "axe", baseAtk: 8, baseSpd: -5 },
      { name: "木杖", type: "weapon", subtype: "staff", baseAtk: 10 },
    ],
    // 區域專屬套裝池
    sets: {
      adventurer: [
        {
          name: "冒險者短劍",
          type: "weapon",
          subtype: "dagger",
          baseAtk: 10,
          setId: "adventurer",
        },
        {
          name: "冒險者皮衣",
          type: "armor_upper",
          baseHp: 50,
          setId: "adventurer",
        },
        {
          name: "冒險者長靴",
          type: "armor_lower",
          baseSpd: 10,
          setId: "adventurer",
        },
        {
          name: "冒險者徽章",
          type: "accessory",
          baseHp: 30,
          setId: "adventurer",
        },
      ],
      forest: [
        {
          name: "精靈長弓",
          type: "weapon",
          subtype: "bow",
          baseAtk: 15,
          baseSpd: 5,
          setId: "forest",
        },
        { name: "藤蔓護甲", type: "armor_upper", baseHp: 80, setId: "forest" },
        { name: "輕靈之靴", type: "armor_lower", baseSpd: 20, setId: "forest" },
        { name: "自然護符", type: "accessory", baseHp: 50, setId: "forest" },
      ],
      miner: [
        {
          name: "精鋼戰錘",
          type: "weapon",
          subtype: "mace",
          baseAtk: 25,
          setId: "miner",
        },
        {
          name: "重型板甲",
          type: "armor_upper",
          baseHp: 150,
          baseSpd: -5,
          setId: "miner",
        },
        { name: "鋼鐵護腿", type: "armor_lower", baseHp: 80, setId: "miner" },
        { name: "礦工頭燈", type: "accessory", baseAtk: 10, setId: "miner" },
      ],
      flame: [
        {
          name: "炎魔之劍",
          type: "weapon",
          subtype: "sword",
          baseAtk: 40,
          setId: "flame",
        },
        { name: "熔岩胸甲", type: "armor_upper", baseHp: 200, setId: "flame" },
        {
          name: "烈焰戰靴",
          type: "armor_lower",
          baseHp: 100,
          baseAtk: 10,
          setId: "flame",
        },
        { name: "火之核心", type: "accessory", baseAtk: 20, setId: "flame" },
      ],
      glacial: [
        {
          name: "冰霜之槍",
          type: "weapon",
          subtype: "sword",
          baseAtk: 50,
          setId: "glacial",
        },
        {
          name: "永凍冰甲",
          type: "armor_upper",
          baseHp: 250,
          baseDef: 0.05,
          setId: "glacial",
        },
        {
          name: "踏雪長靴",
          type: "armor_lower",
          baseHp: 120,
          baseSpd: 15,
          setId: "glacial",
        },
        {
          name: "極寒水晶",
          type: "accessory",
          baseDef: 0.05,
          setId: "glacial",
        },
      ],
      necro: [
        {
          name: "喚靈法杖",
          type: "weapon",
          subtype: "staff",
          baseAtk: 60,
          setId: "necro",
        },
        {
          name: "亡者屍布",
          type: "armor_upper",
          baseHp: 100,
          baseAtk: 20,
          setId: "necro",
        },
        {
          name: "白骨戰靴",
          type: "armor_lower",
          baseHp: 80,
          baseSpd: 10,
          setId: "necro",
        },
        { name: "靈魂容器", type: "accessory", baseAtk: 30, setId: "necro" },
      ],
      sandstorm: [
        {
          name: "蠍刺雙刃",
          type: "weapon",
          subtype: "dagger",
          baseAtk: 70,
          baseCrit: 0.1,
          setId: "sandstorm",
        },
        {
          name: "沙暴風衣",
          type: "armor_upper",
          baseHp: 150,
          baseSpd: 20,
          setId: "sandstorm",
        },
        {
          name: "流沙之靴",
          type: "armor_lower",
          baseHp: 100,
          baseSpd: 30,
          setId: "sandstorm",
        },
        {
          name: "黃金甲蟲",
          type: "accessory",
          baseAtk: 25,
          baseHp: 100,
          setId: "sandstorm",
        },
      ],
      // 狼群套裝
      wolf_pack: [
        {
          name: "狼牙匕首",
          type: "weapon",
          subtype: "dagger",
          baseAtk: 18,
          baseCrit: 0.05,
          setId: "wolf_pack",
        },
        {
          name: "狼皮大衣",
          type: "armor_upper",
          baseHp: 60,
          setId: "wolf_pack",
        },
        { name: "狼嚎指環", type: "accessory", baseAtk: 8, setId: "wolf_pack" },
      ],

      // === 煉獄神話套裝 (Abyssal) ===
      sin: [
        {
          name: "路西法之傲",
          type: "weapon",
          subtype: "sword",
          rarity: "abyssal",
          baseAtk: 2000,
          desc: "攻擊時反彈 20% 傷害給攻擊者。",
          setId: "sin",
        },
        {
          name: "瑪門之貪",
          type: "accessory",
          rarity: "abyssal",
          baseAtk: 500,
          desc: "每擁有 1000G 增加 1% 攻擊力。",
          setId: "sin",
        },
        {
          name: "莉莉絲之吻",
          type: "armor_upper",
          rarity: "abyssal",
          baseHp: 10000,
          desc: "被攻擊時有 10% 機率魅惑敵人。",
          setId: "sin",
        },
        {
          name: "撒旦之怒",
          type: "armor_lower",
          rarity: "abyssal",
          baseHp: 5000,
          baseAtk: 1000,
          desc: "暴擊傷害 +100%。",
          setId: "sin",
        },
      ],

      // === 幻界幻影套裝 (Phantasm) ===
      void: [
        {
          name: "黃衣之王",
          type: "armor_upper",
          rarity: "phantasm",
          baseHp: 8000,
          desc: "理智值消耗減半。",
          setId: "void",
        },
        {
          name: "無面者面具",
          type: "accessory",
          rarity: "phantasm",
          baseSpd: 200,
          desc: "閃避率 +30%，但防禦歸零。",
          setId: "void",
        },
        {
          name: "拉萊耶之鑰",
          type: "weapon",
          subtype: "staff",
          rarity: "phantasm",
          baseAtk: 1500,
          desc: "攻擊無視敵人防禦。",
          setId: "void",
        },
        {
          name: "深潛者之鱗",
          type: "armor_lower",
          rarity: "phantasm",
          baseHp: 4000,
          baseDef: 0.3,
          desc: "受到的物理傷害減半。",
          setId: "void",
        },
      ],
    },
  },

  // --- 6. 套裝效果 (Set Bonuses) ---
  sets: {
    adventurer: {
      name: "新手冒險者",
      bonus2: { maxHp: 50 },
      bonus4: { all_pct: 0.1 },
      bonus6: { hp_regen: 5 },
    },
    wolf_pack: {
      name: "狼群之心",
      bonus2: { speed: 15 },
      bonus4: { crit: 0.1 },
      bonus6: { crit_dmg: 0.5 },
    },
    forest: {
      name: "森之靈",
      bonus2: { dodge: 0.05 },
      bonus4: { hp_regen: 10 },
      bonus6: { speed: 30 },
    },
    miner: {
      name: "堅定意志",
      bonus2: { block: 0.1 },
      bonus4: { maxHp: 300 },
      bonus6: { def: 0.15 },
    },
    flame: {
      name: "火焰行者",
      bonus2: { atk: 30 },
      bonus4: { true_dmg: 20 },
      bonus6: { atk_pct: 0.25 },
    },
    glacial: {
      name: "絕對零度",
      bonus2: { def: 0.1 },
      bonus4: { reflect: 0.2 },
      bonus6: { block: 0.3 },
    },
    necro: {
      name: "亡靈大軍",
      bonus2: { lifesteal: 0.05 },
      bonus4: { atk: 50 },
      bonus6: { maxHp: 500 },
    },
    sandstorm: {
      name: "沙漠風暴",
      bonus2: { speed: 30 },
      bonus4: { dodge: 0.1 },
      bonus6: { true_dmg: 50 },
    },

    // 後期套裝
    sin: {
      name: "七宗罪",
      bonus2: { atk_pct: 0.5 },
      bonus4: { lifesteal: 0.2 },
      bonus6: { true_dmg: 10000 },
    },
    void: {
      name: "虛空行者",
      bonus2: { speed: 100 },
      bonus4: { sanity_regen: 1 },
    }, // 特殊：每層回理智
  },

  // --- 7. 合成與配方 (Recipes) ---
  recipes: [
    {
      name: "中級治療藥水",
      type: "consumable",
      effect: { hp: 100 },
      req: { slime_gel: 5, gold: 50 },
      desc: "效果更好的藥水",
    },
    {
      name: "高級治療藥水",
      type: "consumable",
      effect: { hp: 500 },
      req: { life_seed: 1, gold: 100 },
      desc: "能治療嚴重傷勢",
    },
    {
      name: "特級治療藥水",
      type: "consumable",
      effect: { hp: 2000 },
      req: { life_seed: 5, fire_essence: 2 },
      desc: "瞬間恢復大量生命",
    },

    {
      name: "狼牙項鍊",
      type: "accessory",
      setId: "wolf_pack",
      stats: { atk: 10, crit: 0.05 },
      req: { wolf_fang: 10, gold: 200 },
      desc: "散發著野性的氣息",
    },
    {
      name: "火焰劍",
      type: "weapon",
      setId: "flame",
      stats: { atk: 35 },
      req: { fire_essence: 5, iron_ore: 5 },
      desc: "燃燒著永不熄滅的火焰",
    },

    // 幻界入場道具
    {
      name: "幻界之鑰",
      type: "consumable",
      effect: { open_world: "phantasm" },
      req: { wind_crest: 1, earth_shard: 1, eternal_ember: 1 },
      desc: "通往瘋狂世界的鑰匙，需集齊各區精華。",
    },
  ],

  // --- 8. 素材庫 (Materials) ---
  materials: {
    // 基礎掉落
    slime_gel: { name: "凝膠", value: 5, rarity: "common" },
    wolf_fang: { name: "狼牙", value: 10, rarity: "common" },
    bat_wing: { name: "蝠翼", value: 8, rarity: "common" },
    fur: { name: "獸皮", value: 10, rarity: "common" },
    spider_silk: { name: "蜘蛛絲", value: 12, rarity: "common" },
    cloth: { name: "破布", value: 8, rarity: "common" },

    // 中階材料
    iron_ore: { name: "鐵礦", value: 20, rarity: "uncommon" },
    ancient_wood: { name: "古木", value: 50, rarity: "uncommon" },
    fire_essence: { name: "火精", value: 80, rarity: "rare" },
    hell_leather: { name: "地獄皮", value: 100, rarity: "rare" },
    permafrost: { name: "永凍冰晶", value: 120, rarity: "rare" },
    soul_dust: { name: "靈魂粉末", value: 150, rarity: "rare" },
    sunstone: { name: "太陽石", value: 200, rarity: "rare" },

    // Boss 掉落 (Epic / Legendary)
    wind_crest: { name: "風之紋章", value: 500, rarity: "epic" },
    life_seed: { name: "生命種子", value: 500, rarity: "epic" },
    earth_shard: { name: "大地碎片", value: 1000, rarity: "epic" },
    eternal_ember: { name: "永燃餘燼", value: 1500, rarity: "legendary" },
    frozen_heart: { name: "冰霜之心", value: 1500, rarity: "legendary" },
    cursed_skull: { name: "詛咒頭骨", value: 1500, rarity: "legendary" },
    mirage_sand: { name: "幻象之沙", value: 1500, rarity: "legendary" },

    // 煉獄/幻界素材
    sin_dust: {
      name: "罪孽之塵",
      value: 3000,
      rarity: "abyssal",
      desc: "[煉獄] 惡魔的骨灰。",
    },
    demon_horn: {
      name: "惡魔之角",
      value: 5000,
      rarity: "abyssal",
      desc: "[煉獄] 強大的鍛造材料。",
    },
    pride_crown: {
      name: "傲慢皇冠殘片",
      value: 9999,
      rarity: "abyssal",
      desc: "[煉獄] 挑戰魔王的證明。",
    },

    void_slime: {
      name: "虛空粘液",
      value: 3000,
      rarity: "phantasm",
      desc: "[幻界] 不存在的物質。",
    },
    star_dust: {
      name: "星之彩",
      value: 5000,
      rarity: "phantasm",
      desc: "[幻界] 來自外太空的色彩。",
    },
    elder_sign: {
      name: "舊神印記",
      value: 9999,
      rarity: "phantasm",
      desc: "[幻界] 封印古神的力量。",
    },

    brain_matter: {
      name: "異種大腦",
      value: 4000,
      rarity: "phantasm",
      desc: "[幻界] 脈動著的腦組織。",
    },
    deep_scale: {
      name: "深淵鱗片",
      value: 4000,
      rarity: "phantasm",
      desc: "[幻界] 散發著魚腥味。",
    },
    black_feather: {
      name: "墮天使之羽",
      value: 4000,
      rarity: "abyssal",
      desc: "[煉獄] 染黑的羽毛。",
    },

    // 特殊
    magic_dust: { name: "魔塵", value: 1, desc: "分解裝備的產物。" },
  },

  // --- 9. 事件列表 (Events) ---
  events: [
    { id: "spring", weight: 20, icon: "⛲", name: "治癒之泉" },
    { id: "chest", weight: 25, icon: "📦", name: "寶箱" },
    { id: "merchant", weight: 15, icon: "👳", name: "流浪商人" },
    { id: "crafting", weight: 12, icon: "⚒️", name: "廢棄工作台" },
    { id: "gambler", weight: 8, icon: "🎲", name: "瘋狂賭徒" },
    { id: "alchemist", weight: 8, icon: "🧪", name: "煉金術師" },
    { id: "trap", weight: 10, icon: "🪤", name: "陷阱" },

    // 特殊高階事件 (極低機率)
    {
      id: "demon_contract",
      weight: 1,
      icon: "📜",
      name: "惡魔契約",
      desc: "用靈魂換取力量，但代價是墮入煉獄...",
    },
    {
      id: "sanity_altar",
      weight: 5,
      icon: "🧠",
      name: "理智祭壇",
      desc: "[幻界] 獻祭理智以換取禁忌的知識。",
    },
  ],

  // --- 10. 稀有度設定 (Rarities) ---
  rarity: {
    common: {
      name: "普通",
      color: "text-common",
      border: "border-common",
      mult: 1.0,
    },
    uncommon: {
      name: "優良",
      color: "text-uncommon",
      border: "border-uncommon",
      mult: 1.2,
    },
    rare: {
      name: "稀有",
      color: "text-rare",
      border: "border-rare",
      mult: 1.5,
    },
    epic: {
      name: "史詩",
      color: "text-epic",
      border: "border-epic",
      mult: 2.0,
    },
    legendary: {
      name: "傳說",
      color: "text-legendary",
      border: "border-legendary",
      mult: 3.0,
    },
    // 後期專屬
    phantasm: {
      name: "幻影",
      color: "text-phantasm",
      border: "border-phantasm",
      mult: 5.0,
    }, // 幻界
    abyssal: {
      name: "深淵",
      color: "text-abyssal",
      border: "border-abyssal",
      mult: 10.0,
    }, // 煉獄
  },

  // --- 11. 詞綴系統 (Affixes) ---
  // 僅適用於 Legendary 及以下，Abyssal 與 Phantasm 裝備不受詞綴影響
  affixes: {
    prefixes: [
      { name: "鋒利之", type: "atk", val: 0.1 },
      { name: "堅固之", type: "maxHp", val: 0.1 },
      { name: "輕盈之", type: "speed", val: 0.1 },
      { name: "致命之", type: "crit", val: 0.05, minRarity: "rare" },
      { name: "嗜血之", type: "lifesteal", val: 0.05, minRarity: "epic" },
      { name: "守護之", type: "block", val: 0.05, minRarity: "rare" },
      { name: "狂暴之", type: "atk", val: 0.2, minRarity: "epic" },
    ],
    suffixes: [
      { name: "狼", type: "flat_atk", val: 5 },
      { name: "熊", type: "flat_hp", val: 20 },
      { name: "鷹", type: "flat_spd", val: 5 },
      { name: "巨象", type: "flat_hp", val: 50, minRarity: "rare" },
      { name: "猛虎", type: "flat_atk", val: 15, minRarity: "rare" },
    ],
  },
};
